import type { CollectionWatch } from "@/types";
import { photo, photoFiles } from "@/lib/images";

export const mensWatches: CollectionWatch[] = [
  {
    id: "m1",
    name: "Heritage Open Heart",
    brand: "IWC Schaffhausen",
    price: "$8,450",
    tag: "AUTOMATIC",
    image: photo(photoFiles.men.iwcHeritage),
  },
  {
    id: "m2",
    name: "Blue Chronograph",
    brand: "Zonatime Sport",
    price: "$2,150",
    tag: "CHRONO",
    image: photo(photoFiles.men.blueChrono),
  },
  {
    id: "m3",
    name: "Classic Automatic",
    brand: "Seiko",
    price: "$420",
    tag: "23 JEWELS",
    image: photo(photoFiles.men.seikoDial),
  },
  {
    id: "m4",
    name: "Midnight Chronograph",
    brand: "Casio",
    price: "$285",
    tag: "WATER RESIST",
    image: photo(photoFiles.men.casioMidnight),
  },
  {
    id: "m5",
    name: "Tourbillon Edition",
    brand: "Seiko",
    price: "$1,890",
    tag: "24 JEWELS",
    image: photo(photoFiles.men.seikoMovement),
  },
  {
    id: "m6",
    name: "Presage Open Heart",
    brand: "Seiko Presage",
    price: "$650",
    tag: "AUTOMATIC",
    image: photo(photoFiles.men.seikoPresage),
  },
  {
    id: "m7",
    name: "Geneve Collection",
    brand: "Hublot",
    price: "$12,200",
    tag: "LIMITED",
    image: photo(photoFiles.men.hublotGeneve),
  },
  {
    id: "m8",
    name: "Blue Sunburst",
    brand: "Citizen",
    price: "$380",
    tag: "AUTOMATIC",
    image: photo(photoFiles.men.citizenBlue),
  },
  {
    id: "m9",
    name: "Santos Classic",
    brand: "Cartier",
    price: "$6,750",
    tag: "ICONIC",
    image: photo(photoFiles.men.cartierSantos),
  },
  {
    id: "m10",
    name: "Seamaster Pro",
    brand: "Omega",
    price: "$5,400",
    tag: "300M",
    image: photo(photoFiles.men.omegaSeamaster),
  },
  {
    id: "m11",
    name: "Minimal Steel",
    brand: "Timex",
    price: "$195",
    tag: "ESSENTIAL",
    image: photo(photoFiles.men.timexMinimal),
  },
];

export const womensWatches: CollectionWatch[] = [
  {
    id: "w1",
    name: "Skyline Gold",
    brand: "Zonatime Élégance",
    price: "$1,340",
    tag: "ROSE GOLD",
    image: photo(photoFiles.women.skyGold),
  },
  {
    id: "w2",
    name: "Heritage Petite",
    brand: "Zonatime Couture",
    price: "$980",
    tag: "LEATHER",
    image: photo(photoFiles.women.portraitGold),
  },
  {
    id: "w3",
    name: "Emerald Petite",
    brand: "Zonatime Élégance",
    price: "$1,240",
    tag: "ROSE GOLD",
    image: photo(photoFiles.women.yellowPurple),
  },
  {
    id: "w4",
    name: "Malachite Green",
    brand: "Zonatime",
    price: "$890",
    tag: "GREEN DIAL",
    image: photo(photoFiles.women.emeraldMalachite),
  },
  {
    id: "w5",
    name: "Rose Blush",
    brand: "Lola Rose",
    price: "$760",
    tag: "MALACHITE",
    image: photo(photoFiles.women.lolaRosePink),
  },
  {
    id: "w6",
    name: "Malachite Duo",
    brand: "Lola Rose",
    price: "$890",
    tag: "GREEN DIAL",
    image: photo(photoFiles.women.lolaRoseGreen),
  },
  {
    id: "w7",
    name: "Festive Trio",
    brand: "Zonatime Gift",
    price: "$1,120",
    tag: "SET",
    image: photo(photoFiles.women.festiveCollection),
  },
  {
    id: "w8",
    name: "Two-Tone Classic",
    brand: "Zonatime",
    price: "$720",
    tag: "BESTSELLER",
    image: photo(photoFiles.women.twoToneClassic),
  },
  {
    id: "w9",
    name: "Pearl & Lace",
    brand: "Zonatime Couture",
    price: "$980",
    tag: "LUXURY",
    image: photo(photoFiles.women.pearlLace),
  },
];
